baseURL = "https://wooa.dev/"
languageCode = "ko-kr"
title = "WOOA.DEV"
theme = "hugo-book"

enableRobotsTXT = true

[params]
  BookTheme = "auto"
  BookToC = true
  BookSection = "docs"
  BookRepo = "https://github.com/devwooops/wooa.dev"
  BookEditPath = "edit/main"

[params.BookSearch]
  enabled = true
